// Generated by gencpp from file value_msg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef VALUE_MSG_MESSAGE_ADDTWOINTS_H
#define VALUE_MSG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <value_msg/AddTwoIntsRequest.h>
#include <value_msg/AddTwoIntsResponse.h>


namespace value_msg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace value_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::value_msg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::value_msg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::value_msg::AddTwoInts > {
  static const char* value()
  {
    return "value_msg/AddTwoInts";
  }

  static const char* value(const ::value_msg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::value_msg::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::value_msg::AddTwoInts > 
template<>
struct MD5Sum< ::value_msg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::value_msg::AddTwoInts >::value();
  }
  static const char* value(const ::value_msg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::value_msg::AddTwoIntsRequest> should match 
// service_traits::DataType< ::value_msg::AddTwoInts > 
template<>
struct DataType< ::value_msg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::value_msg::AddTwoInts >::value();
  }
  static const char* value(const ::value_msg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::value_msg::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::value_msg::AddTwoInts > 
template<>
struct MD5Sum< ::value_msg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::value_msg::AddTwoInts >::value();
  }
  static const char* value(const ::value_msg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::value_msg::AddTwoIntsResponse> should match 
// service_traits::DataType< ::value_msg::AddTwoInts > 
template<>
struct DataType< ::value_msg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::value_msg::AddTwoInts >::value();
  }
  static const char* value(const ::value_msg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VALUE_MSG_MESSAGE_ADDTWOINTS_H
